/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.telecom.fise2.view;

import fr.telecom.fise2.controller.Listeners;
import fr.telecom.fise2.model.Functionalities;

/**
 *
 * @author Arnaud
 */

public class CalculatorFrame extends javax.swing.JFrame {

    protected static String op=null; // Chaine de caractères correspondant au calcul souhaité
    protected static float partie1; // Partie gauche du calcul
    protected static float partie2; // Partie droite du calcul
    protected static int pos; // Position de l'opérateur
   
    
    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents(); // On initialise les composants
        Functionalities.resetLabels(ErrorNbrLabel, ChooseOpLabel, ErrorOpLabel, ValidLabel,Div0Label,VirguleLabel);
        // On fait appel à la fonction resetLabels pour rendre invisble les labels d'erreurs
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Input = new javax.swing.JTextField();
        Butt0 = new javax.swing.JButton();
        Butt1 = new javax.swing.JButton();
        Butt2 = new javax.swing.JButton();
        Butt3 = new javax.swing.JButton();
        Butt4 = new javax.swing.JButton();
        Butt5 = new javax.swing.JButton();
        Butt6 = new javax.swing.JButton();
        Butt7 = new javax.swing.JButton();
        Butt8 = new javax.swing.JButton();
        Butt9 = new javax.swing.JButton();
        ButtAdd = new javax.swing.JButton();
        ButtSub = new javax.swing.JButton();
        ButtMult = new javax.swing.JButton();
        ButtDiv = new javax.swing.JButton();
        ButtModulo = new javax.swing.JButton();
        ButtEnter = new javax.swing.JButton();
        ButtClear = new javax.swing.JButton();
        ErrorOpLabel = new javax.swing.JLabel();
        ButtSuppr = new javax.swing.JButton();
        ValidLabel = new javax.swing.JLabel();
        ButtNeg = new javax.swing.JButton();
        ErrorNbrLabel = new javax.swing.JLabel();
        ChooseOpLabel = new javax.swing.JLabel();
        Div0Label = new javax.swing.JLabel();
        ButtDot = new javax.swing.JButton();
        VirguleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Input.setAlignmentX(0.0F);
        Input.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 63;
        gridBagConstraints.ipadx = 433;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 97, 0, 0);
        getContentPane().add(Input, gridBagConstraints);

        Butt0.setText("0");
        Butt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 97, 0, 0);
        getContentPane().add(Butt0, gridBagConstraints);

        Butt1.setText("1");
        Butt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        getContentPane().add(Butt1, gridBagConstraints);

        Butt2.setText("2");
        Butt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        getContentPane().add(Butt2, gridBagConstraints);

        Butt3.setText("3");
        Butt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        getContentPane().add(Butt3, gridBagConstraints);

        Butt4.setText("4");
        Butt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 97);
        getContentPane().add(Butt4, gridBagConstraints);

        Butt5.setText("5");
        Butt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 97, 0, 0);
        getContentPane().add(Butt5, gridBagConstraints);

        Butt6.setText("6");
        Butt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(Butt6, gridBagConstraints);

        Butt7.setText("7");
        Butt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(Butt7, gridBagConstraints);

        Butt8.setText("8");
        Butt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(Butt8, gridBagConstraints);

        Butt9.setText("9");
        Butt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.Butt9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 97);
        getContentPane().add(Butt9, gridBagConstraints);

        ButtAdd.setText("+");
        ButtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 97, 0, 0);
        getContentPane().add(ButtAdd, gridBagConstraints);

        ButtSub.setText("-");
        ButtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtSubActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(ButtSub, gridBagConstraints);

        ButtMult.setText("*");
        ButtMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtMultActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        getContentPane().add(ButtMult, gridBagConstraints);

        ButtDiv.setText("/");
        ButtDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtDivActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        getContentPane().add(ButtDiv, gridBagConstraints);

        ButtModulo.setText("%");
        ButtModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtModuloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 97);
        getContentPane().add(ButtModulo, gridBagConstraints);

        ButtEnter.setText("Enter");
        ButtEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtEnterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 49, 97);
        getContentPane().add(ButtEnter, gridBagConstraints);

        ButtClear.setText("Clear");
        ButtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 49, 0);
        getContentPane().add(ButtClear, gridBagConstraints);

        ErrorOpLabel.setForeground(new java.awt.Color(255, 0, 0));
        ErrorOpLabel.setText("Veuillez ne pas écrire 2 opérateurs à la suite");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 31, 0, 0);
        getContentPane().add(ErrorOpLabel, gridBagConstraints);

        ButtSuppr.setText("Suppr");
        ButtSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtSupprActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 49, 0);
        getContentPane().add(ButtSuppr, gridBagConstraints);

        ValidLabel.setForeground(new java.awt.Color(255, 0, 0));
        ValidLabel.setText("Veuillez valider votre première opération avant d'en faire une deuxième");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 152, 0, 0);
        getContentPane().add(ValidLabel, gridBagConstraints);

        ButtNeg.setText("+ / -");
        ButtNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtNegActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 97, 49, 0);
        getContentPane().add(ButtNeg, gridBagConstraints);

        ErrorNbrLabel.setForeground(new java.awt.Color(255, 0, 0));
        ErrorNbrLabel.setText("Vous n'avez pas saisi assez de chiffres ou un mauvais caractère");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 168, 0, 0);
        getContentPane().add(ErrorNbrLabel, gridBagConstraints);

        ChooseOpLabel.setForeground(new java.awt.Color(255, 0, 0));
        ChooseOpLabel.setText("Veuillez choisir un opérateur avant de valider");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(ChooseOpLabel, gridBagConstraints);

        Div0Label.setForeground(new java.awt.Color(255, 0, 0));
        Div0Label.setText("Veuillez ne pas faire de division par 0");
        Div0Label.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 46, 0, 0);
        getContentPane().add(Div0Label, gridBagConstraints);

        ButtDot.setText(".");
        ButtDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listeners.ButtDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 49, 0);
        getContentPane().add(ButtDot, gridBagConstraints);

        VirguleLabel.setForeground(new java.awt.Color(255, 0, 0));
        VirguleLabel.setText("Vous avez déjà un nombre à virgule");
        VirguleLabel.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 46, 0, 0);
        getContentPane().add(VirguleLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }
    
    // On met en privé tous les boutons et en protected static les labels et l'input(JTextField)
    //Afin de pouvoir y accéder dans les Listeners
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butt0;
    private javax.swing.JButton Butt1;
    private javax.swing.JButton Butt2;
    private javax.swing.JButton Butt3;
    private javax.swing.JButton Butt4;
    private javax.swing.JButton Butt5;
    private javax.swing.JButton Butt6;
    private javax.swing.JButton Butt7;
    private javax.swing.JButton Butt8;
    private javax.swing.JButton Butt9;
    private javax.swing.JButton ButtAdd;
    private javax.swing.JButton ButtClear;
    private javax.swing.JButton ButtDiv;
    private javax.swing.JButton ButtDot;
    private javax.swing.JButton ButtEnter;
    private javax.swing.JButton ButtModulo;
    private javax.swing.JButton ButtMult;
    private javax.swing.JButton ButtNeg;
    private javax.swing.JButton ButtSub;
    private javax.swing.JButton ButtSuppr;
    protected static javax.swing.JLabel ChooseOpLabel;
    protected static javax.swing.JLabel Div0Label;
    protected static javax.swing.JLabel ErrorNbrLabel;
    protected static javax.swing.JLabel ErrorOpLabel;
    protected static javax.swing.JTextField Input;
    protected static javax.swing.JLabel ValidLabel;
    protected static javax.swing.JLabel VirguleLabel;
    // End of variables declaration//GEN-END:variables

}
